hdfs dfs -mkdir /VictimasDeHomicidioPorSexo
hdfs dfs -mkdir  /VictimasDeHomicidio
hdfs dfs -mkdir /FertilidadAdolescentesPor1000 
hdfs dfs -mkdir /MuertesPorCancer
hdfs dfs -mkdir /MuertesPorCardiovascular
hdfs dfs -mkdir /MuertesPorRespiratorio
hdfs dfs -mkdir /MuertesComunicables
hdfs dfs -mkdir /MuertesNoComunicables
hdfs dfs -mkdir /MuertesHeridas
hdfs dfs -mkdir /MediaEdad
hdfs dfs -mkdir /PoblacionTotal
hdfs dfs -mkdir /MuertesBebes
hdfs dfs -mkdir /FertilidadTotal
hdfs dfs -mkdir /GastoEnSaludNoDelTotal
hdfs dfs -mkdir /ExpectativaDeVida
hdfs dfs -mkdir /TurismoEntrante
hdfs dfs -mkdir /TurismoSaliente
hdfs dfs -mkdir /GastoEnSalud